version: '3.8'

services:
  flux:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    image: arsen3d/flux:latest
    ports:
      - "7860:7860"
    networks:
      - localnet
networks:
  localnet:
    external: true